[package]
name = "StensWebsite"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.40.0", features = ["full"]}
tera = "1.20.0"
tower = "0.5.0"
tower-http = { version = "0.5.2", features = ["fs"] }